.gitignore, .travis.yml, plugins/html-elements-plugin/src/test/resources/config/application.properties, plugins/jdi-elements-plugin/src/test/resources/config/application.properties, plugins/mobile-plugin/src/test/java/pagefactory/mobile/CucumberTest.java, plugins/web-plugin/src/main/java/ru/sbtqa/tag/pagefactory/web/capabilities/WebDriverCapabilitiesParser.java, plugins/web-plugin/src/test/resources/config/application.properties
add chrome addon to travis
use headles chrome for tests
=> fix desired capabilities parser

plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/EndpointEntry.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/EndpointEntryReflection.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/annotation/applicators/QueryApplicator.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/manager/EndpointManager.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/properties/ApiConfiguration.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/utils/FromResponseUtils.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/utils/PathUtils.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/utils/PlaceholderUtils.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/utils/TemplateUtils.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/stepdefs/ApiSetupSteps.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/stepdefs/ApiSteps.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/stepdefs/en/ApiStepDefs.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/stepdefs/ru/ApiStepDefs.java, plugins/rest-plugin/src/test/java/ru/sbtqa/tag/api/junit/JunitTests.java, plugins/rest-plugin/src/test/resources/features/FillFromFeature.feature, plugins/web-plugin/src/main/java/ru/sbtqa/tag/pagefactory/web/checks/WebPageChecks.java
* Добавлена возможность добалять в плейсхолдеры в path.
* Исправлены некоторые регекспы степ дефов
* Добавлена опция для использования ssl relaxed
* Испрвлены некоторые баги
=> Chang rest-plugin because of example

plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/drivers/MobileDriverService.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/properties/MobileConfiguration.java, plugins/mobile-plugin/src/test/resources/config/application.properties-sample
https://github.com/sbtqa/page-factory/pull/158
=> add reset strategy

page-factory-core/src/main/java/ru/sbtqa/tag/stepdefs/en/CoreStepDefs.java, page-factory-core/src/main/java/ru/sbtqa/tag/stepdefs/ru/CoreStepDefs.java
Добавила новый регексп для заполнения многострочных полей ввода
Пример:
* заполняет поле "Поле ввода в несколько строк"
"""
новое значение
новое значение
"""
=> added new regexp for fill

page-factory-api/src/main/java/ru/sbtqa/tag/pagefactory/environment/Environment.java
Поправила, чтобы рефлекшены не перетирались на ниже уровнем, чем есть
=> fix reflection

plugins/web-plugin/src/main/java/ru/sbtqa/tag/pagefactory/web/drivers/WebDriverService.java
=> added file decorator

page-factory-core/pom.xml, plugins/html-plugin/pom.xml, plugins/jdi-plugin/pom.xml, pom.xml
=> Update to latest selenium 3.141.59

page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/aspects/report/Click.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/aspects/report/Fill.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/aspects/report/PressKey.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/aspects/report/Select.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/aspects/report/SetCheckbox.java
Минимальный фикс по выводу параметров в отчеты
=> parameters aspects

plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/junit/ApiStepsImpl.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/storage/BlankStorage.java
=> remove blank after sending

pom.xml
Features:
* Get non-value as json string https://github.com/sbtqa/datajack/pull/31
* Strict key existance for Stash https://github.com/sbtqa/datajack/pull/30
=> New datajack version.

page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/reflection/DefaultReflection.java
=> fix wrong parameters count in actions

page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/reflection/DefaultReflection.java, plugins/web-plugin/src/test/java/pagefactory/pages/webelements/ContactPage.java, plugins/web-plugin/src/test/java/pagefactory/stepdefs/TestSteps.java, plugins/web-plugin/src/test/resources/features/list.feature
corrected comparison of types of actions
fix #209
=> corrected comparison of types of actions

plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/EndpointEntry.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/EndpointEntryReflection.java, plugins/rest-plugin/src/test/java/ru/sbtqa/tag/api/entries/apirequest/RequestEndpointEntry.java, plugins/rest-plugin/src/test/java/ru/sbtqa/tag/api/entries/methods/PostEndpointEntry.java
Resolves https://github.com/sbtqa/page-factory-2/issues/189
=> Add ability to override fields in constructor

page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/aspects/FragmentsAspect.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/utils/GherkinResource.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/utils/GherkinSerializer.java
Add the possibility to work option --step-notifications with fragments feature
=> Step notifications

plugins/web-plugin/src/main/java/ru/sbtqa/tag/pagefactory/web/checks/WebPageChecks.java, plugins/web-plugin/src/main/java/ru/sbtqa/tag/pagefactory/web/junit/WebStepsImpl.java, plugins/web-plugin/src/main/java/ru/sbtqa/tag/pagefactory/web/utils/ElementUtils.java, plugins/web-plugin/src/main/java/ru/sbtqa/tag/stepdefs/en/WebStepDefs.java, plugins/web-plugin/src/main/java/ru/sbtqa/tag/stepdefs/ru/WebStepDefs.java, plugins/web-plugin/src/main/resources/i18n/webstepsimpl/en.properties, plugins/web-plugin/src/main/resources/i18n/webstepsimpl/ru.properties, plugins/web-plugin/src/test/resources/features/stash.feature
added step - stores value from field in stash
=> stores value from field in stash

page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/PageManager.java
=> Fix NPE on PageManager if no pages.package property provided

page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/utils/GherkinSerializer.java
=> Fix pipe escaping in data table cells

page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/aspects/CriticalStepCheckAspect.java
=> Do not try to take screenshot if no driver initialized

plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/annotation/applicators/QueryApplicator.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/utils/PlaceholderUtils.java, plugins/rest-plugin/src/test/java/ru/sbtqa/tag/api/endpoints/ClientJsonEndpoint.java, plugins/rest-plugin/src/test/java/ru/sbtqa/tag/api/entries/methods/DeleteEndpointEntry.java, plugins/rest-plugin/src/test/resources/features/Endpoints.feature
=> fix query placeholder replace

page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/reflection/DefaultReflection.java
=> Fix NPE on parameters compare in DefaultReflection

pom.xml
=> Update datajack version to 5.0.2

page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/allure/JunitReporter.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/utils/MD5.java, plugins/html-plugin/src/main/java/ru/sbtqa/tag/pagefactory/utils/TestIdUtils.java
=> Fix allure lifecycle

plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/storage/EndpointBlank.java
=> fix cookie adding in endpoint blank

.travis.yml, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/junit/CoreStepsImpl.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/utils/PathUtils.java, page-factory-core/src/main/java/ru/sbtqa/tag/stepdefs/en/CoreStepDefs.java, page-factory-core/src/main/java/ru/sbtqa/tag/stepdefs/ru/CoreStepDefs.java, plugins/html-plugin/src/main/java/ru/sbtqa/tag/stepdefs/en/HtmlStepDefs.java, plugins/html-plugin/src/main/java/ru/sbtqa/tag/stepdefs/ru/HtmlStepDefs.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/actions/MobilePageActions.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/drivers/MobileDriverService.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/junit/MobileStepsImpl.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/properties/MobileConfiguration.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/utils/AppiumVideoRecorder.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/stepdefs/en/MobileStepDefs.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/stepdefs/ru/MobileStepDefs.java, plugins/mobile-plugin/src/test/resources/config/application.properties-sample, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/EndpointEntry.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/manager/EndpointManager.java, pom.xml
=> Appium video

pom.xml
=> update qa-utils version

page-factory-doc/src/main/asciidoc/common_properties.asciidoc
update data about config DTagConfigFileFolder and DTagConfigFile
=> update data about path config

plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/drivers/MobileDriverService.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/properties/MobileConfiguration.java
add important capabilities for run test on real ios devices
=> add important capabilities for run test on real ios devices

page-factory-api/src/main/java/ru/sbtqa/tag/pagefactory/environment/Environment.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/aspects/CriticalStepCheckAspect.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/junit/CoreSetupSteps.java, page-factory-core/src/main/java/ru/sbtqa/tag/stepdefs/en/CoreStepDefs.java, page-factory-core/src/main/java/ru/sbtqa/tag/stepdefs/ru/CoreStepDefs.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/drivers/MobileDriverService.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/properties/MobileConfiguration.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/utils/AppiumVideoRecorder.java
1. В Environment теперь складывается текущий сценарий
2. В названии видео на appium используется имя сценария
3. noReset и fullReset вынесены в конфигурацию как отдельные параметры
4. deviceUdId удален из MobileDriverService
=> Mobile video

page-factory-core/src/main/java/ru/sbtqa/tag/stepdefs/ru/CoreStepDefs.java
=> fix clear field bug

.travis.yml, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/data/DataReplacer.java, plugins/html-plugin/src/test/resources/config/application.properties, plugins/web-plugin/src/test/resources/config/application.properties
=> Fix ccsexception

pom.xml
=> Update Datajack to 5.1.2

page-factory-api/src/main/java/ru/sbtqa/tag/pagefactory/context/PageContext.java, page-factory-api/src/main/java/ru/sbtqa/tag/pagefactory/environment/Environment.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/PageManager.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/junit/CoreSetupSteps.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/tasks/TaskHandler.java, plugins/html-plugin/src/main/java/ru/sbtqa/tag/pagefactory/html/junit/HtmlSetupSteps.java, plugins/html-plugin/src/main/java/ru/sbtqa/tag/stepdefs/en/HtmlStepDefs.java, plugins/html-plugin/src/main/java/ru/sbtqa/tag/stepdefs/ru/HtmlStepDefs.java, plugins/html-plugin/src/test/java/ru/sbtqa/tag/pagefactory/JunitTest.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/pagefactory/mobile/junit/MobileSetupSteps.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/stepdefs/en/MobileStepDefs.java, plugins/mobile-plugin/src/main/java/ru/sbtqa/tag/stepdefs/ru/MobileStepDefs.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/context/EndpointContext.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/environment/ApiEnvironment.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/junit/ApiSetupSteps.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/stepdefs/en/ApiStepDefs.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/stepdefs/ru/ApiStepDefs.java, plugins/web-plugin/src/test/java/pagefactory/JunitTest.java
=> Memory leaks

plugins/rest-plugin/pom.xml, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/junit/ApiStepsImpl.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/storage/EndpointBlank.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/utils/ReflectionUtils.java, plugins/rest-plugin/src/test/java/ru/sbtqa/tag/api/JunitTests.java, plugins/rest-plugin/src/test/java/ru/sbtqa/tag/api/endpoints/ClientJsonEndpoint.java, plugins/rest-plugin/src/test/java/ru/sbtqa/tag/api/entries/template/ReplacerEntry.java, plugins/rest-plugin/src/test/resources/data/Positive.json
=> Allow json primitive types as values

page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/data/DataFactory.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/properties/Configuration.java, page-factory-doc/src/main/asciidoc/cucumber_data.asciidoc
=> Add ability to set custom test data provider

page-factory-core/src/main/java/ru/sbtqa/tag/stepdefs/ru/CoreStepDefs.java, plugins/html-plugin/src/test/resources/config/application.properties, plugins/web-plugin/src/test/resources/config/application.properties
=> [Bugfix][#352] Russian steps throw NPE where is used ContainCondition

.travis.yml, page-factory-api/src/main/java/ru/sbtqa/tag/pagefactory/annotations/rest/Endpoint.java, page-factory-doc/src/main/asciidoc/rest_entries.asciidoc, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/EndpointEntry.java, plugins/rest-plugin/src/main/java/ru/sbtqa/tag/api/utils/PlaceholderUtils.java, plugins/rest-plugin/src/test/java/ru/sbtqa/tag/api/JunitTests.java, plugins/rest-plugin/src/test/java/ru/sbtqa/tag/api/entries/apirequest/CustomHost.java, plugins/rest-plugin/src/test/java/ru/sbtqa/tag/api/entries/template/TypedArraysEntry.java, plugins/rest-plugin/src/test/resources/features/Host.feature
=> add custom host-port to Endpoint

plugins/html-plugin/src/main/java/ru/sbtqa/tag/pagefactory/html/junit/HtmlStepsImpl.java
=> добавил вывод наименования поля в шаге "проверяет форму"

page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/capabilities/SelenoidCapabilitiesParser.java, page-factory-core/src/main/java/ru/sbtqa/tag/pagefactory/properties/Configuration.java
=> add skin parameter

.travis.yml, .travis/pushback.sh
bump pf2 version in pf2-example project
=> test pushback to pf-example in branch

page-factory-doc/src/main/asciidoc/web_elements.asciidoc, plugins/html-plugin/src/main/java/ru/sbtqa/tag/pagefactory/HTMLPage.java, plugins/html-plugin/src/main/java/ru/sbtqa/tag/pagefactory/html/loader/CustomHtmlElementLoader.java, plugins/html-plugin/src/main/java/ru/sbtqa/tag/pagefactory/html/properties/HtmlConfiguration.java, plugins/html-plugin/src/main/java/ru/sbtqa/tag/pagefactory/reflection/HtmlReflection.java, plugins/html-plugin/src/main/java/ru/sbtqa/tag/pagefactory/utils/HtmlElementUtils.java
=> add ability to specify decorator in properties
